##Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {sseg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
set_property PACKAGE_PIN W6 [get_ports {sseg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
set_property PACKAGE_PIN U8 [get_ports {sseg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
set_property PACKAGE_PIN V8 [get_ports {sseg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
set_property PACKAGE_PIN U5 [get_ports {sseg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
set_property PACKAGE_PIN V5 [get_ports {sseg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]
set_property PACKAGE_PIN U7 [get_ports {sseg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]

set_property PACKAGE_PIN V7 [get_ports {sseg[7]}]							
	set_property IOSTANDARD LVCMOS33 [get_ports {sseg[7]}]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

set_property PACKAGE_PIN L1 [get_ports {lfsr_bitstream[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[13]}]
set_property PACKAGE_PIN P1 [get_ports {lfsr_bitstream[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[12]}]
set_property PACKAGE_PIN N3 [get_ports {lfsr_bitstream[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[11]}]
set_property PACKAGE_PIN P3 [get_ports {lfsr_bitstream[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[10]}]
set_property PACKAGE_PIN U3 [get_ports {lfsr_bitstream[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[9]}]
set_property PACKAGE_PIN W3 [get_ports {lfsr_bitstream[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[8]}]
set_property PACKAGE_PIN V3 [get_ports {lfsr_bitstream[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[7]}]
set_property PACKAGE_PIN V13 [get_ports {lfsr_bitstream[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[6]}]
set_property PACKAGE_PIN V14 [get_ports {lfsr_bitstream[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[5]}]
set_property PACKAGE_PIN U14 [get_ports {lfsr_bitstream[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[4]}]
set_property PACKAGE_PIN U15 [get_ports {lfsr_bitstream[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[3]}]
set_property PACKAGE_PIN W18 [get_ports {lfsr_bitstream[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[2]}]
set_property PACKAGE_PIN V19 [get_ports {lfsr_bitstream[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[1]}]
set_property PACKAGE_PIN U19 [get_ports {lfsr_bitstream[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lfsr_bitstream[0]}]

##SWITCH SW15 FOR "reset"
set_property PACKAGE_PIN R2 [get_ports reset]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
	
##LED LD15 FOR "clr"
set_property PACKAGE_PIN U16 [get_ports max_t]						
	set_property IOSTANDARD LVCMOS33 [get_ports max_t]